services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    App\EventListener\ProfilerDisableListener:
        arguments:
            $profiler: "@profiler"
        tags:
            -   name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
