## Exclude external libraries:
exclude_paths:
- "config.guess"
- "config.sub"
- "lib/vendor/"
- "www/js/ace/"
- "www/js/flot/"
- "www/js/jquery*.js"
- "www/js/jscolor.js"
- "www/js/js.cookie*.js"
- "www/js/sorttable.js"
- "www/js/tabber.js"
