engines:
  phpmd:
    enabled: true
    config:
## Don't use the 'controversial' ruleset:
      rulesets: "cleancode,codesize,design,naming,unusedcode"
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false

## Simply include all files for GPA ratings:
ratings:
  paths:
  - "**"

## Excluded files, e.g. external libraries:
exclude_paths:
- "config.guess"
- "config.sub"
- "lib/vendor/"
- "www/js/ace/"
- "www/js/flot/"
- "www/js/jquery*.js"
- "www/js/jscolor.js"
- "www/js/js.cookie*.js"
- "www/js/sorttable.js"
- "www/js/tabber.js"
