legacy.public_problems:
    path: /public/problems.php
legacy.public_problem:
    path: /public/problem.php
legacy.public_team:
    path: /public/team.php
legacy.team_index:
    path: /team/
legacy.team_problem:
    path: /team/problem.php
legacy.team_team:
    path: /team/team.php
