legacy.index:
    path: /
legacy.public:
    path: /public/
legacy.public_problem:
    path: /public/problem.php
legacy.public_team:
    path: /public/team.php
legacy.jury_clarification:
    path: /jury/clarification.php
legacy.team_index:
    path: /team/
legacy.team_problem:
    path: /team/problem.php
legacy.team_team:
    path: /team/team.php
legacy.jury_contest:
    path: /jury/contest.php

legacy.jury_checkconfig:
    path: /jury/checkconfig.php
legacy.jury_impexp:
    path: /jury/impexp.php
legacy.jury_genpasswds:
    path: /jury/genpasswds.php


legacy.jury_delete:
    path: /jury/delete.php
