legacy.index:
    path: /
legacy.public:
    path: /public/
legacy.public_problem:
    path: /public/problem.php
legacy.public_team:
    path: /public/team.php
legacy.jury_team:
    path: /jury/team.php
legacy.jury_problem:
    path: /jury/problem.php
legacy.jury_export_problem:
    path: /jury/export_problem.php
legacy.jury_judgehosts:
    path: /jury/judgehosts.php
legacy.jury_judgehost:
    path: /jury/judgehost.php
legacy.jury_internal_errors:
    path: /jury/internal_errors.php
legacy.jury_internal_error:
    path: /jury/internal_error.php
legacy.jury_judgehost_restrictions:
    path: /jury/judgehost_restrictions.php
legacy.jury_judgehost_restriction:
    path: /jury/judgehost_restriction.php
legacy.jury_clarification:
    path: /jury/clarification.php
legacy.jury_language:
    path: /jury/language.php
legacy.jury_rejudge:
    path: /jury/rejudge.php
legacy.jury_rejudging:
    path: /jury/rejudging.php
legacy.team_index:
    path: /team/
legacy.team_problem:
    path: /team/problem.php
legacy.team_team:
    path: /team/team.php
legacy.jury_contest:
    path: /jury/contest.php
legacy.jury_executable:
    path: /jury/executable.php
legacy.jury_finalize:
    path: /jury/finalize.php

legacy.jury_checkconfig:
    path: /jury/checkconfig.php
legacy.jury_impexp:
    path: /jury/impexp.php
legacy.jury_genpasswds:
    path: /jury/genpasswds.php
legacy.jury_refresh_cache:
    path: /jury/refresh_cache.php
legacy.jury_check_judgings:
    path: /jury/check_judgings.php


legacy.jury_delete:
    path: /jury/delete.php
legacy.jury_user:
    path: /jury/user.php
legacy.jury_team_category:
    path: /jury/team_category.php
legacy.jury_team_affiliation:
    path: /jury/team_affiliation.php
legacy.jury_change_contest:
    path: /jury/change_contest.php
legacy.jury_toggle_notify:
    path: /jury/toggle_notify.php
legacy.jury_ignore_submission:
    path: /jury/ignore.php
legacy.jury_verify:
    path: /jury/verify.php
legacy.jury_testcase:
    path: /jury/testcase.php
legacy.jury_team_output:
    path: /jury/team_output.php

legacy.jury_ajax_problems:
    path: /jury/ajax_problems.php
legacy.jury_ajax_teams:
    path: /jury/ajax_teams.php
legacy.jury_ajax_languages:
    path: /jury/ajax_languages.php
