domjudge:
    resource: '@DOMJudgeBundle/Controller/'
    type: annotation
    prefix: /

domjudge_api_v4:
    type: rest
    resource: '@DOMJudgeBundle/Controller/APIController.php'
    prefix: /api/v4
    defaults: { _format: "json" }

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

logout:
    path: /logout

overriden_routes:
    resource: "@DOMJudgeBundle/Resources/config/routing.yml"

fallback:
    path: /{path}
    defaults: { _controller: "LegacyBundle\\Controller\\FallbackController:fallback" }
    requirements:
        path: .*

legacy_routes:
    resource: "@LegacyBundle/Resources/config/routing.yml"
