domjudge:
    resource: '@DOMJudgeBundle/Controller/'
    type: annotation
    prefix: /

api:
    type: rest
    resource: '@DOMJudgeBundle/Resources/config/routing_api.yml'

logout:
    path: /logout

overriden_routes:
    resource: "@DOMJudgeBundle/Resources/config/routing.yml"

fallback:
    path: /{path}
    defaults: { _controller: "LegacyBundle\\Controller\\FallbackController:fallback" }
    requirements:
        path: .*

legacy_routes:
    resource: "@LegacyBundle/Resources/config/routing.yml"
