# app:
    # resource: '@AppBundle/Controller/'
    # type: annotation

fallback:
    path: /{path}
    defaults: { _controller: "legacy.controller.fallback:fallback" }
    requirements:
        path: .*
