services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DOMJudgeBundle\EventListener\ProfilerDisableListener:
        arguments:
            $profiler: "@profiler"
        tags:
            - name: kernel.event_listener
              event: kernel.request
              method: onKernelRequest
