# Default DOMjudge bundle configuration. Load this file in app/config/config.yml
domjudge:
  api:
    endpoints:
      contests:
        url: /
      judgement-types:
        tables: []
        externalidfield: ~
      languages: ~
      problems:
        tables: [problem, contestproblem]
      groups:
        tables: [team_category]
        externalidfield: ~
      organizations:
        tables: [team_affiliation]
      teams:
        tables: [team, contestteam]
      teams-members:
        tables: []
      submissions:
        type: live
        externalidfield: ~
      judgements:
        type: live
        tables: [judging]
        externalidfield: ~
      runs:
        type: live
        tables: [judging_run]
        externalidfield: ~
      clarifications:
        type: live
        contestidfield: cid
      awards:
        type: aggregate
        tables: []
        externalidfield: ~
      scoreboard:
        type: aggregate
        tables: []
        externalidfield: ~
      event-feed:
        type: aggregate
        tables: [event]
        externalidfield: ~
      # From here are DOMjudge extensions:
      users:
        url: ~
        externalidfield: ~
      testcases:
        url: ~
        externalidfield: ~
