# Default DOMjudge bundle configuration. Load this file in app/config/config.yml
domjudge:
  api:
    endpoints:
      contests:
        url: /
        primarykey: cid
      judgement-types:
        tables: []
        externalid: ~
      languages:
        primarykey: langid
      problems:
        tables: [problem, contestproblem]
        primarykey: probid
      groups:
        tables: [team_category]
        externalid: ~
        primarykey: categoryid
      organizations:
        tables: [team_affiliation]
        primarykey: affilid
      teams:
        tables: [team, contestteam]
        primarykey: teamid
      teams-members:
        tables: []
      submissions:
        type: live
        externalid: ~
        primarykey: submitid
      judgements:
        type: live
        tables: [judging]
        externalid: ~
        primarykey: judgingid
      runs:
        type: live
        tables: [judging_run]
        externalid: ~
        primarykey: runid
      clarifications:
        type: live
        contestid: cid
        primarykey: clarid
      awards:
        type: aggregate
        tables: []
        externalid: ~
      scoreboard:
        type: aggregate
        tables: []
        externalid: ~
      event-feed:
        type: aggregate
        tables: [event]
        externalid: ~
        primarykey: eventid
      # From here are DOMjudge extensions:
      users:
        url: ~
        externalid: ~
        primarykey: userid
      testcases:
        url: ~
        externalid: ~
        primarykey: testcaseid

