# Seperate API routing file as we need the name_prefix key here and that requires a separate file

domjudge_api_v4:
    type: rest
    resource: '@DOMJudgeBundle/Controller/APIController.php'
    prefix: /api/v4
    defaults: { _format: "json" }

domjudge_api_v4_new:
    type: rest
    resource: '@DOMJudgeBundle/Controller/API/'
    prefix: /api/v4/contests/{cid}
    name_prefix: domjudge_api_v4
    defaults: { _format: "json" }
